### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by brookleberry** [bbaxa16/transcending-care#1]
Create a responsive, functional nav bar - a combination of icons or simple text labels. Utilizing [fontawesome.io](http://fontawesome.io/) for icons.

- login
- register
- logout
- user profile
- forum

**Comment by alexandraalday** [comment]
Can I claim this one?

**Comment by brookleberry** [comment]
For sure

**Comment by alexandraalday** [comment]
navbar pull request in and ready for your review. https://github.com/bbaxa16/transcending-care/pull/5 

we can add styles, links, etc in a later issue once we get the backend working.
